### ISSUE TITLE
Change default branch name from `master` to `main`

### ISSUE THREAD

**Issue by bishwasgautam** [amjadodeh/noteful#1]
```
Unhandled rejection Error: Command failed: git -C ./amjadodeh/noteful checkout master
error: pathspec 'master' did not match any file(s) known to git

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:671:12)
```

**Comment by amjadodeh** [comment]
![image](https://user-images.githubusercontent.com/69196058/100139764-f3ad7700-2e5d-11eb-8122-380aad2266f8.png)

?

**Comment by bishwasgautam** [comment]
Sorry, this was meant for a different repository. Please ignore it!

**Comment by amjadodeh** [comment]
Ha No worries. Take care.
